name: Auto update

on:
  # Check new version weekly at 05:00 AM on Monday UTC
  schedule:
    - cron: "0 5 * * 1"

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  check-update:
    name: Check Update
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Update
        run: make update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update PHP
