name: CI

on:
  # Build the nightly version at at 7:15 AM on Saturday UTC
  # schedule:
  #   - cron: "15 7 * * 6"

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.generate-jobs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: generate-jobs
        name: Generate Jobs
        run: |
          matrix=$(./.github/workflows/generate.sh)
          jq . <<<"$matrix" # sanity check / debugging aid
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  test:
    name: Build and test
    needs: generate-jobs
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-jobs.outputs.matrix) }}
    env:
      DOCKER_IMAGE: ghcr.io/oanhnn/php
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=${{ matrix.php }}-${{ matrix.variant }}
          labels: |
            org.opencontainers.image.title=The PHP Docker Image
            org.opencontainers.image.description=The PHP Docker Image base from PHP official images and installed some useful PHP extensions
            org.opencontainers.image.author=oanhnn

      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache-${{ matrix.php }}-${{ matrix.variant }}
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache-${{ matrix.php }}-${{ matrix.variant }},mode=max
          context: ${{ matrix.php }}/${{ matrix.variant }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
          load: true

      - name: Test
        run: |
          docker run ${{ env.DOCKER_IMAGE }}:${{ matrix.php }}-${{ matrix.variant }} php -v
          docker run ${{ env.DOCKER_IMAGE }}:${{ matrix.php }}-${{ matrix.variant }} php -m

      - name: Check vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.DOCKER_IMAGE }}:${{ matrix.php }}-${{ matrix.variant }}
          args: --file=${{ matrix.php }}/${{ matrix.variant }}/Dockerfile --exclude-base-image-vulns

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
