name: CI

on:
  # Build the nightly version at at 7:15 AM on Saturday UTC
  schedule:
    - cron: "15 7 * * 6"

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.4'
          - '8.0'
        variant:
          - apache
          - cli
          - fpm
          - zts
          - cli-alpine
          - fpm-alpine
    env:
      DOCKER_IMAGE: oanhnn/php
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          if [[ "${{ matrix.variant }}" =~ ^.*alpine$ ]]; then BASE_OS="alpine"; else BASE_OS="buster"; fi
          # Set step output
          echo "::set-output name=base_os::$(echo $BASE_OS)"
          echo "::set-output name=version::$(echo ${{ matrix.php }}-${{ matrix.variant }})"
          echo "::set-output name=created::$(date --utc --iso-8601=seconds | sed 's/+00.00/Z/g')"

      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: VERSION=${{ steps.prepare.outputs.version }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:${{ steps.prepare.outputs.version }}
          cache-to: type=inline
          context: ${{ matrix.php }}/${{ steps.prepare.outputs.base_os }}
          pull: true
          load: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.prepare.outputs.version }}

      - name: Test
        run: |
          docker run ${{ env.DOCKER_IMAGE }}:${{ steps.prepare.outputs.version }} php -v
          docker run ${{ env.DOCKER_IMAGE }}:${{ steps.prepare.outputs.version }} php -m

      - uses: Azure/container-scan@v0
        with:
          image-name: ${{ env.DOCKER_IMAGE }}:${{ steps.prepare.outputs.version }}
          severity-threshold: MEDIUM