name: Verify Templating

on:
  # Check new version in the nightly at 7:15 AM on Saturday UTC
  schedule:
    - cron: "15 7 * * 6"

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  apply-templates:
    name: Check For Uncomitted Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Apply Templates
        run: make generate
      - name: Check Git Status
        run: |
          status="$(git status --short)"
          [ -z "$status" ]
